import type { Post } from "@/types/posts";

export const posts: Post[] = [
  {
    id: 1,
    title: "Wpis testowy",
    content: "To mój pierwszy post.",
    createdAt: new Date().toISOString(),
    author: "John Doe",
    category: "Programming",
    tags: ["JavaScript", "TypeScript", "Vue"],
    image: "https://picsum.photos/200",
    slug: "wpis-testowy",
    shortDescription: "To mój pierwszy post na blogu.",
    isFeatured: true,
    isPublished: true,
    isArchived: false,
  },
  {
    id: 2,
    title: "Drugi wpis",
    content: "To jest mój drugi post na blogu.",
    createdAt: new Date().toISOString(),
    author: "John Doe",
    category: "Programming",
    tags: ["JavaScript", "TypeScript"],
    image: "https://picsum.photos/200",
    slug: "wpis-testowy",
    shortDescription: "To mój pierwszy post na blogu.",
    isFeatured: true,
    isPublished: true,
    isArchived: false,
  },
  {
    id: 3,
    title: "Trzeci wpis",
    content: "To jest mój trzeci post na blogu.",
    createdAt: new Date().toISOString(),
    author: "John Nick",
    category: "UI",
    tags: ["JavaScript", "TypeScript"],
    image: "https://picsum.photos/200",
    slug: "wpis-testowy",
    shortDescription: "To mój pierwszy post na blogu.",
    isFeatured: true,
    isPublished: true,
    isArchived: false,
  },
  {
    id: 4,
    title: "Czwarty wpis",
    content: "To jest mój czwarty post na blogu.",
    createdAt: new Date().toISOString(),
    author: "John Nick",
    category: "WCAG",
    tags: ["JavaScript", "TypeScript"],
    image: "https://picsum.photos/200",
    slug: "wpis-testowy",
    shortDescription: "To mój pierwszy post na blogu.",
    isFeatured: true,
    isPublished: true,
    isArchived: false,
  },
  {
    id: 5,
    title: "Czwarty wpis",
    content: "To jest mój czwarty post na blogu.",
    createdAt: new Date().toISOString(),
    author: "John Nick",
    category: "JavaScript",
    tags: ["JavaScript", "TypeScript"],
    image: "https://picsum.photos/200",
    slug: "wpis-testowy",
    shortDescription: "To mój pierwszy post na blogu.",
    isFeatured: true,
    isPublished: true,
    isArchived: false,
  },
  {
    id: 6,
    title: "Szósty wpis",
    content: "To jest mój szósty post na blogu.",
    createdAt: new Date().toISOString(),
    author: "John Nick",
    category: "Vue",
    tags: ["JavaScript", "TypeScript"],
    image: "https://picsum.photos/200",
    slug: "wpis-testowy",
    shortDescription: "To mój pierwszy post na blogu.",
    isFeatured: true,
    isPublished: true,
    isArchived: false,
  },
];

export default defineEventHandler(() => {
  return posts;
});
